/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"



void
cal_1(char *host, int x, int z, int opc)
{
	CLIENT *clnt;
	int  *result_1;
	struct Parametros  suma_1_arg;
	int  *result_2;
	struct Parametros  resta_1_arg;
	int  *result_3;
	struct Parametros  multiplicacion_1_arg;
	int  *result_4;
	struct Parametros  division_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, cal, calc_ver, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
/*SE HACE LA COMPROBACION DEL RESULTADO*/
/*suma*/
	suma_1_arg.a=x;
	suma_1_arg.b=z;
/*resta*/
	resta_1_arg.a = x;
	resta_1_arg.b = z;
/*multiplicacion*/	
multiplicacion_1_arg.a=x;
multiplicacion_1_arg.b=z;
/*division*/
division_1_arg.a=x;
division_1_arg.b=z;
	/*ººa punta a la estructuraºº*/

switch (opc)
{
case 1:
	/* code */
	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	/*MOSTRAR RESULTADO*/
	printf("El resultado de la suma es: %d\n", *result_1);

	break;
case 2:
	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("El resultado de la resta es: %d\n", *result_2);
	break;

case 3:

	result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("El resultado de la multiplicacion es: %d\n", *result_3);
	break;

case 4:

	result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("El resultado de la division es: %d\n", *result_4);
	break;

default:
	
	break;
}
	


	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int x, z;
	int opc = 0;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	/* Se piden los valores para los parametros*/
	/*se muestra un menu al usuario*/
	do{
	printf("MENU DE OPCIONES \n");
	printf("1. Suma: \n");
	printf("2. Resta: \n");
	printf("3. Multiplicacion: \n");
	printf("4. Division: \n");
	printf("5. SALIR. \n");	
	printf(" \n");	printf(" \n");	
	scanf("%d", &opc);

	switch (opc)
	{
	case 1:
		/* code */
		printf("Hello, estas en el proceso de suma\n");
		printf("Ingrese primer parametro: \n");
		scanf("%d", &x);
		printf("Ingrese segundo parametro: \n");
		scanf("%d", &z);

		break;

	case 2:
		printf("Hello, estas en el proceso de resta\n");
		printf("Ingrese primer parametro: \n");
		scanf("%d", &x);
		printf("Ingrese segundo parametro: \n");
		scanf("%d", &z);

		break;
	
	case 3:
		printf("Hello, estas en el proceso de multiplicacion\n");
		printf("Ingrese el parametro multiplicando: \n");
		scanf("%d", &x);
		printf("Ingrese el parametro multiplicador: \n");
		scanf("%d", &z);

		break;
	
	case 4:
		printf("Hello, estas en el proceso de division\n");
		printf("Ingrese el parametro dividendo: \n");
		scanf("%d", &x);
		printf("Ingrese el parametro divisor(=!0): \n");
		scanf("%d", &z);
		if (z==0)
		{
			/* code */
			printf("NO SE PUEDE DIVIDIR ENTRE CERO \n");
			do{
				printf("Ingrese el parametro divisor(=!0): \n");
				printf("DEBE SER UN VALOR DIFERENTE A 0: \n");
				scanf("%d", &z);

			}while (z==0);

		}
		

		break;
	case 5:
	printf("SEE YOU SOON...");

		break;
	
	default:
		printf("opcion no valida.\n");
		

		break;
	}
	
	
	cal_1 (host, x, z, opc);
	}while (opc!=5);
	
	
	
	

	

	
exit (0);
}
